'use client';

import { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, CalendarDays, ChevronLeft, ChevronRight,
  Database, HeartPulse, LayoutDashboard, ShieldCheck, SlidersHorizontal, Syringe, TrendingUp,
} from 'lucide-react';
import { Area, CartesianGrid, ComposedChart, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type ClinicalDatum={date:string;region:string;pathogen:string;count:number};
type WWDatum={date:string;region:string;pathogen:string;value:number};
type ClinicalData={meta:{sourceSnapshot:string;dateRange:string[];regionDateRanges?:Record<string,string[]>};regions:string[];pathogens:string[];series:ClinicalDatum[]};
type WWData={meta:{dateRange:string[];generatedAt:string;methodChangeDate:string};regions:string[];pathogens:string[];series:WWDatum[]};
type VaccinationRecord={region:string;ageGroup:string;count:number;percent:number};
type VaccinationData={meta:{generatedAt:string;scope:string};snapshots:{snapshotDate:string;sourceUpdatedAt:string;records:VaccinationRecord[]}[]};
type MortalityDatum={week:string;date:string;region:string;count:number};
type MortalityData={meta:{dateRange:string[];sourceUpdatedAt:string;status:string};series:MortalityDatum[]};
type Point={date:string;value:number};
type Mode='clinical'|'wastewater'; type Model='weekoverweek'|'linear'; type ViewMode='monitor'|'explore';

const fmt=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'});
const shortFmt=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short'});
const numberFmt=new Intl.NumberFormat('en-GB');
const mean=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;
const clamp=(v:number,l:number,h:number)=>Math.max(l,Math.min(h,v));
const dateLabel=(v:string)=>fmt.format(new Date(`${v}T12:00:00`));
const shift=(d:string,n:number)=>{const x=new Date(`${d}T12:00:00`);x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const ageDays=(d:string)=>Math.floor((Date.now()-new Date(`${d}T12:00:00`).getTime())/86400000);

function analyse(base:Point[],requested:string,mode:Mode,model:Model){
  const reserve=mode==='clinical'?14:2;let found=base.findIndex(d=>d.date>=requested);if(found<0)found=base.length-1;const chosen=clamp(base[found]?.date===requested?found:found-1,mode==='clinical'?13:1,base.length-reserve-1);
  const smooth=base.map((d,i)=>({...d,smooth:mean(base.slice(Math.max(0,i-(mode==='clinical'?6:1)),i+1).map(x=>x.value))}));
  let current=0,previous=0,slope=0,relChange=0,relativeChangeAvailable=true,sigma=1,predictions:any[]=[];
  if(mode==='wastewater'){
    current=smooth[chosen].smooth;previous=smooth[chosen-1].smooth;slope=current-previous;const recentScale=mean(smooth.slice(Math.max(0,chosen-12),chosen+1).map(d=>Math.abs(d.smooth)));const baselineFloor=Math.max(Number.EPSILON,recentScale*.01);relativeChangeAvailable=Math.abs(previous)>=baselineFloor;relChange=relativeChangeAvailable?(current-previous)/Math.abs(previous):0;
    const diffs=smooth.slice(Math.max(1,chosen-8),chosen+1).map((d,i,a)=>i?d.smooth-a[i-1].smooth:NaN).filter(Number.isFinite);sigma=Math.max(Number.EPSILON,Math.sqrt(mean(diffs.map(x=>x*x))));predictions=[1,2].map(h=>{const pred=Math.max(0,current+slope*h),w=1.96*sigma*Math.sqrt(h);return{date:shift(base[chosen].date,h*7),prediction:pred,bandRange:[Math.max(0,pred-w),pred+w]}});
  }else{
    const currentWeek=mean(base.slice(chosen-6,chosen+1).map(d=>d.value));previous=mean(base.slice(chosen-13,chosen-6).map(d=>d.value));const fit=smooth.slice(chosen-13,chosen+1),xm=6.5,ym=mean(fit.map(d=>d.smooth));const ls=fit.reduce((s,d,i)=>s+(i-xm)*(d.smooth-ym),0)/fit.reduce((s,_d,i)=>s+(i-xm)**2,0),ll=ym+ls*(13-xm);current=model==='linear'?Math.max(0,ll):currentWeek;slope=model==='linear'?ls:(currentWeek-previous)/7;relChange=model==='linear'?slope*7/Math.max(current,1):(currentWeek-previous)/Math.max(previous,1);const res=model==='linear'?fit.map((d,i)=>d.smooth-(ll+ls*(i-13))):[...base.slice(chosen-13,chosen-6).map(d=>d.value-previous),...base.slice(chosen-6,chosen+1).map(d=>d.value-currentWeek)];sigma=Math.max(1,Math.sqrt(mean(res.map(x=>x*x))));predictions=Array.from({length:14},(_,o)=>{const h=o+1,p=Math.max(0,current+slope*h),w=1.96*sigma*Math.sqrt(1+h/14);return{date:shift(base[chosen].date,h),prediction:p,bandRange:[Math.max(0,p-w),p+w]}});
  }
  const lookback=mode==='clinical'?83:51,start=Math.max(0,chosen-lookback);const observed=smooth.slice(start,chosen+1).map(d=>({...d,observed:d.value}));const errors:number[]=[];const horizon=mode==='clinical'?7:1;
  for(let i=Math.max(mode==='clinical'?14:2,chosen-(mode==='clinical'?90:26));i<=chosen-horizon;i++){if(mode==='wastewater'){const p=Math.max(0,smooth[i].smooth+(smooth[i].smooth-smooth[i-1].smooth));errors.push(Math.abs(smooth[i+1].smooth-p))}else{const cur=mean(base.slice(i-6,i+1).map(d=>d.value)),prev=mean(base.slice(i-13,i-6).map(d=>d.value));const lf=smooth.slice(i-13,i+1),lm=mean(lf.map(d=>d.smooth));const ls=lf.reduce((s,d,j)=>s+(j-6.5)*(d.smooth-lm),0)/lf.reduce((s,_d,j)=>s+(j-6.5)**2,0),ll=lm+ls*6.5;const p=model==='linear'?Math.max(0,ll+ls*7):Math.max(0,cur+(cur-prev));errors.push(Math.abs(smooth[i+7].smooth-p))}}
  const mae=mean(errors),scale=Math.max(Number.EPSILON,mean(smooth.slice(start,chosen+1).map(d=>Math.abs(d.smooth)))),nmae=mae/scale,reliability=clamp(1-(nmae-.2)/.4,0,1),alert=relativeChangeAvailable?(relChange>.5?'Red':relChange>.2?'Yellow':'Green'):'Not assessed';return{chart:[...observed,...predictions],current,previous,slope,relChange,relativeChangeAvailable,mae,nmae,reliability,alert,date:base[chosen].date,maxDate:base[base.length-reserve-1].date};
}

function MonitorView({clinical,ww,vaccination,mortality}:{clinical:ClinicalData;ww:WWData;vaccination:VaccinationData;mortality:MortalityData}){
  const virusOverview=clinical.regions.filter(r=>r!=='All regions').map(region=>{const end=clinical.meta.regionDateRanges?.[region]?.[1]||clinical.meta.dateRange[1],weekStart=shift(end,-6),previousStart=shift(end,-13),previousEnd=shift(end,-7);return{region,end,viruses:clinical.pathogens.map(pathogen=>{const rows=clinical.series.filter(d=>d.region===region&&d.pathogen===pathogen),count=rows.filter(d=>d.date>=weekStart&&d.date<=end).reduce((sum,d)=>sum+d.count,0),previous=rows.filter(d=>d.date>=previousStart&&d.date<=previousEnd).reduce((sum,d)=>sum+d.count,0),change=previous>=10&&count>=10?(count-previous)/previous:null;return{pathogen,count,change}})}});
  const clinicalEnd=clinical.meta.dateRange[1];
  const vaccine=vaccination.snapshots.at(-1)!;
  const maxCoverage=Math.max(...vaccine.records.map(r=>r.percent),1);
  const mortalityLatest=mortality.meta.dateRange[1];
  const mortalityCards=mortality.series.filter(d=>d.date===mortalityLatest).map(latest=>{const history=mortality.series.filter(d=>d.region===latest.region&&d.date<mortalityLatest);const previous=history.at(-1);return{...latest,change:previous&&previous.count?((latest.count-previous.count)/previous.count)*100:null}});
  const sources=[
    {name:'Wastewater',date:ww.meta.dateRange[1],state:ageDays(ww.meta.dateRange[1])<=21?'Current':'Delayed',note:'SLU / SEEC'},
    {name:'Vaccination',date:vaccine.snapshotDate,state:ageDays(vaccine.snapshotDate)>90?'Seasonal pause':'Current',note:'FHM / NVR'},
    {name:'Mortality',date:mortalityLatest,state:'Preliminary',note:'SCB'},
    {name:'Clinical research',date:clinical.meta.dateRange[1],state:'Snapshot',note:'Three-region dataset'},
  ];
  return <section className="monitor-workspace">
    <div className="monitor-layout">
      <div className="monitor-main">
        <section className="virus-panel"><div className="panel-title"><div><Activity size={18}/><span><strong>Clinical activity overview</strong><small>Healthcare encounters during each region’s latest complete seven-day period</small></span></div></div>
          <div className="clinical-matrix"><div className="matrix-head"><span>Indicator</span>{virusOverview.map(group=><span key={group.region}><strong>{group.region}</strong><small>to {shortFmt.format(new Date(`${group.end}T12:00:00`))}</small></span>)}</div>{clinical.pathogens.map(pathogen=><div className="matrix-row" key={pathogen}><strong>{pathogen}</strong>{virusOverview.map(group=>{const item=group.viruses.find(v=>v.pathogen===pathogen)!;return <span key={group.region}><b>{numberFmt.format(item.count)}</b><small className={item.change===null?'not-assessed':item.change>.5?'red':item.change>.2?'yellow':'green'}>{item.change===null?'N/A':`${item.change>=0?'+':''}${(item.change*100).toFixed(0)}%`}</small></span>})}</div>)}</div>
        </section>
        <section className="warning-panel paused"><div className="panel-title"><div><AlertTriangle size={18}/><span><strong>Signals requiring attention</strong><small>Changes and alerts resume when current clinical data are available</small></span></div><span className="warning-count">—</span></div>
          <div className="alerts-paused"><ShieldCheck size={20}/><div><strong>Current alerts paused</strong><p>The clinical snapshot ends {dateLabel(clinicalEnd)}. Historical percentages remain visible when both seven-day periods contain at least 10 encounters; low-count comparisons are marked N/A.</p></div></div>
        </section>
        <section className="vaccination-panel"><div className="panel-title"><div><Syringe size={18}/><span><strong>COVID-19 vaccination coverage</strong><small>Current seasonal coverage · FHM National Vaccination Register</small></span></div><span className="panel-date">{dateLabel(vaccine.snapshotDate)}</span></div>
          <div className="coverage-grid">{['Östergötland','Jönköping','Kalmar'].map(region=><article key={region}><h3>{region}</h3>{vaccine.records.filter(r=>r.region===region).map(record=><div className="coverage-row" key={record.ageGroup}><div><span>{record.ageGroup}</span><strong>{record.percent.toFixed(1)}%</strong></div><div className="coverage-track"><i style={{width:`${record.percent/maxCoverage*100}%`}}/></div><small>{numberFmt.format(record.count)} vaccinated</small></div>)}</article>)}</div>
        </section>
        <section className="mortality-panel"><div className="panel-title"><div><HeartPulse size={18}/><span><strong>All-cause mortality</strong><small>Context indicator · not attributable to a specific pathogen</small></span></div><span className="panel-date">Week ending {dateLabel(mortalityLatest)}</span></div>
          <div className="mortality-grid">{mortalityCards.map(item=><article key={item.region}><span>{item.region}</span><strong>{item.count}</strong><small>deaths · {item.change===null?'change unavailable':`${item.change>=0?'+':''}${item.change.toFixed(0)}% week over week`}</small></article>)}</div>
          <p className="qualification">SCB figures for the latest calendar year are preliminary and subject to revision. This indicator provides health-system context and does not identify cause of death.</p>
        </section>
      </div>
      <aside className="source-panel"><div className="panel-title"><div><Database size={18}/><span><strong>Data source status</strong><small>Coverage and publication timing</small></span></div></div>{sources.map(source=><div className="source-row" key={source.name}><span className={`source-dot ${source.state.toLowerCase().replace(' ','-')}`}></span><div><strong>{source.name}</strong><small>{source.note}</small></div><div><strong>{dateLabel(source.date)}</strong><small>{source.state}</small></div></div>)}<div className="privacy-note"><ShieldCheck size={18}/><p><strong>Aggregate outputs only</strong><span>No personal identifiers or raw regional records are published in this interface.</span></p></div></aside>
    </div>
  </section>;
}

function ExploreView({clinical,ww}:{clinical:ClinicalData;ww:WWData}){
  const[mode,setMode]=useState<Mode>('clinical'),[region,setRegion]=useState('Östergötland'),[pathogen,setPathogen]=useState('Influenza'),[analysisDate,setAnalysisDate]=useState('2025-02-15'),[model,setModel]=useState<Model>('weekoverweek');
  const active=mode==='clinical'?clinical:ww;const result=useMemo(()=>{const base=active.series.filter((d:any)=>d.region===region&&d.pathogen===pathogen).map((d:any)=>({date:d.date,value:mode==='clinical'?d.count:d.value}));return base.length?analyse(base,analysisDate,mode,model):null},[active,region,pathogen,analysisDate,mode,model]);
  function changeMode(next:Mode){setMode(next);const d=next==='clinical'?clinical:ww;setRegion(d.regions.includes(region)?region:d.regions[0]);setPathogen(next==='clinical'?'Influenza':'Influenza A+B');setAnalysisDate(d.meta.dateRange[1]);if(next==='wastewater')setModel('weekoverweek')}
  function move(days:number){if(result)setAnalysisDate(clampDate(shift(result.date,days),active.meta.dateRange[0],result.maxDate))}const clampDate=(d:string,a:string,b:string)=>d<a?a:d>b?b:d;
  if(!result)return null;
  const trend=!result.relativeChangeAvailable?(result.slope>0?'Increasing':result.slope<0?'Decreasing':'Stable'):Math.abs(result.relChange)<.1?'Stable':result.relChange>0?'Increasing':'Decreasing',reliability=result.reliability>=.67?'High':result.reliability>=.33?'Moderate':'Low',isWW=mode==='wastewater',unit=isWW?'PMMoV-normalized signal':'encounters per day';
  return <section className="workspace"><div className="heading-row"><div><p className="eyebrow">Exploratory analysis · {isWW?'Wastewater':'Clinical surveillance'}</p><h1>{pathogen} in {region}</h1><p>{isWW?'Weekly wastewater measurements, causal trend and a two-week outlook.':'Observed healthcare encounters, causal trend and a transparent 14-day outlook.'}</p></div><div className="snapshot"><CalendarDays size={17}/><span>Analysis date<strong>{dateLabel(result.date)}</strong></span></div></div>
  <div className="filterbar six"><label>Data type<select value={mode} onChange={e=>changeMode(e.target.value as Mode)}><option value="clinical">Clinical</option><option value="wastewater">Wastewater</option></select></label><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}>{active.regions.map(x=><option key={x}>{x}</option>)}</select></label><label>Pathogen<select value={pathogen} onChange={e=>setPathogen(e.target.value)}>{active.pathogens.map(x=><option key={x}>{x}</option>)}</select></label><label>Age<select disabled><option>All ages</option></select></label><label>Sex<select disabled><option>All sexes</option></select></label><label>Model<select value={model} disabled={isWW} onChange={e=>setModel(e.target.value as Model)}><option value="weekoverweek">{isWW?'Weekly trend':'Week-over-week'}</option>{!isWW&&<option value="linear">Local linear trend</option>}</select></label><div className="date-control"><span>Historical replay</span><div><button aria-label="Previous period" onClick={()=>move(-7)}><ChevronLeft size={17}/></button><input type="date" value={result.date} min={active.meta.dateRange[0]} max={result.maxDate} onChange={e=>setAnalysisDate(e.target.value)}/><button aria-label="Next period" onClick={()=>move(7)}><ChevronRight size={17}/></button></div></div></div>
  <div className="metrics"><article><span>Current level</span><strong>{result.current.toPrecision(3)}</strong><small>{unit}</small></article><article><span>{isWW?'Weekly':'7-day'} change</span><strong className={result.relativeChangeAvailable?(result.relChange>=0?'up':'down'):undefined}>{result.relativeChangeAvailable?(result.relChange>=0?'+':'')+(result.relChange*100).toFixed(0)+'%':'N/A'}</strong><small>{isWW?'versus previous sample':model==='linear'?'model projection':'versus previous week'}</small></article><article><span>Trend</span><strong>{trend}</strong><small>{Math.abs(result.slope).toPrecision(2)} {isWW?'signal/week':'encounters/day²'}</small></article><article><span>Alert</span><strong className={`alert ${result.alert.toLowerCase().replace(' ','-')}`}><i></i>{result.alert}</strong><small>{result.relativeChangeAvailable?'20% / 50% thresholds':'Previous level too close to zero'}</small></article><article><span>Forecast reliability</span><strong>{reliability}</strong><small>{(result.reliability*100).toFixed(0)}% score · NMAE {(result.nmae*100).toFixed(0)}%</small></article></div>
  <div className="content-grid"><article className="chart-card"><div className="card-head"><div><h2>Activity and short-term forecast</h2><p>Real-time view uses only observations available on the analysis date.</p></div><div className="legend"><span className="dot observed"></span>{isWW?'Samples':'Daily encounters'} <span className="line smooth"></span>{isWW?'2-sample mean':'7-day mean'} <span className="line forecast"></span>Forecast</div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={result.chart} margin={{top:18,right:20,bottom:4,left:-12}}><CartesianGrid stroke="#dbe5e2" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>shortFmt.format(new Date(`${v}T12:00:00`))} minTickGap={38} tick={{fontSize:11,fill:'#62716e'}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11,fill:'#62716e'}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={dateLabel} contentStyle={{borderRadius:10,border:'1px solid #dbe5e2'}}/><Area dataKey="bandRange" stroke="none" fill="#a6c9c3" fillOpacity={.28}/><Line dataKey="observed" stroke="#a9b6b3" strokeWidth={0} dot={{r:2.5,fill:'#768581',stroke:'none'}} isAnimationActive={false}/><Line dataKey="smooth" stroke="#123f3a" strokeWidth={2.6} dot={false} connectNulls/><Line dataKey="prediction" stroke="#d16f3f" strokeWidth={2.8} strokeDasharray="7 5" dot={false} connectNulls/><ReferenceLine x={result.date} stroke="#8d9a97" strokeDasharray="3 4" label={{value:'Analysis date',position:'insideTopLeft',fill:'#62716e',fontSize:11}}/>{isWW&&<ReferenceLine x={ww.meta.methodChangeDate} stroke="#b46a48" strokeDasharray="2 3" label={{value:'Method update',position:'insideBottomRight',fill:'#9a5636',fontSize:10}}/>}</ComposedChart></ResponsiveContainer></div></article>
  <aside className="insight-card"><div className="insight-icon"><TrendingUp size={19}/></div><p className="eyebrow">Model interpretation</p><h2>{isWW?(result.relativeChangeAvailable?'The latest wastewater level was '+Math.abs(result.relChange*100).toFixed(0)+'% '+(result.relChange>=0?'higher':'lower')+' than the previous sample.':'The latest wastewater level increased from a near-zero baseline, so a percentage change is not meaningful.'):model==='linear'?`The local trend projects a ${Math.abs(result.relChange*100).toFixed(0)}% ${result.relChange>=0?'increase':'decrease'} over seven days.`:`The last week was ${Math.abs(result.relChange*100).toFixed(0)}% ${result.relChange>=0?'higher':'lower'} than the week before.`}</h2><p>{isWW?'Wastewater uses weekly PMMoV-normalized samples. Age and sex do not apply. Values from week 36 of 2026 use an updated laboratory method.':model==='linear'?'A straight line is fitted to the last 14 causal seven-day means.':'Two complete seven-day periods are compared to reduce weekday artefacts.'}</p><div className="reliability"><div><ShieldCheck size={18}/><span>Historical reliability<strong>{reliability}</strong></span></div><div className="meter"><i style={{width:`${result.reliability*100}%`}}></i></div><small>Mean absolute error: {result.mae.toPrecision(3)}</small></div></aside></div>
  <footer><span>{isWW?'Open aggregate environmental surveillance data · No individual records':'Aggregate counts only · No personal identifiers included'}</span><span>{active.meta.dateRange[0]} — {active.meta.dateRange[1]}</span></footer></section>;
}

export default function Home(){
  const[clinical,setClinical]=useState<ClinicalData|null>(null),[ww,setWW]=useState<WWData|null>(null),[vaccination,setVaccination]=useState<VaccinationData|null>(null),[mortality,setMortality]=useState<MortalityData|null>(null),[view,setView]=useState<ViewMode>('monitor');
  useEffect(()=>{Promise.all([
    fetch('/data/vacceval.json').then(r=>r.json()),fetch('/data/wastewater.json').then(r=>r.json()),
    fetch('/data/vaccination.json').then(r=>r.json()),fetch('/data/mortality.json').then(r=>r.json()),
  ]).then(([a,b,c,d])=>{setClinical(a);setWW(b);setVaccination(c);setMortality(d)})},[]);
  if(!clinical||!ww||!vaccination||!mortality)return<main className="loading">Loading VaccEval surveillance data…</main>;
  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark"><Activity size={19}/></span><div><strong>{view==='monitor'?'VaccEval Surveillance Monitor':'VaccEval'}</strong><span>{view==='monitor'?'Aggregate decision support':'Infectious disease surveillance'}</span></div></div><nav className="view-switch" aria-label="Workspace mode"><button className={view==='monitor'?'selected':''} onClick={()=>setView('monitor')}><LayoutDashboard size={15}/>Monitor</button><button className={view==='explore'?'selected':''} onClick={()=>setView('explore')}><SlidersHorizontal size={15}/>Explore</button></nav><div className="status"><span></span>Automated aggregate surveillance</div><button className="method">Methodology</button></header>
  {view==='monitor'?<MonitorView clinical={clinical} ww={ww} vaccination={vaccination} mortality={mortality}/>:<ExploreView clinical={clinical} ww={ww}/>}<div className="acknowledgement">VaccEval results · Developed and maintained by <a href="https://signalprofessor.se" target="_blank" rel="noreferrer">Signalprofessor</a>.</div></main>;
}
